# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/km0e"

[social.params]
icon = "brand-github"

[[social]]
identifier = "email"
name = "Email"
url = "mailto:kmdr.error@gmail.com"

[social.params]
icon = "brand-gmail"

# [[social]]
# identifier = "twitter"
# name = "Twitter"
# url = "https://twitter.com"

# [social.params]
# icon = "brand-twitter"
